This update addresses a problem with compilation of TDM under all versions of GCC which results in compiler errors like this (along with many others):
   idlib/geometry/RenderMatrix.cpp:45:20: fatal error: intrin.h: No such file or directory

This problem was introduced when the 'idlib/geometry/RenderMatrix.cpp' file
was added, in SVN revision #6685.

The patch associated with this update was provided by 'Hamlet' (circa 21 Dec
2016):

   http://forums.thedarkmod.com/topic/18570-my-experience-with-the-dark-mod-under-linux/#entry399077

(A portion of that same patch ["Add a source file that was left behind into
the Linux source list."] was already committed as part of SVN #6733.)

The patch was provided with the following explanation:

   Also remove a part that is MicroSoft C-dependent and that is optional (fortunately).

Additional testing of the patch under various environments is discussed here:

   http://forums.thedarkmod.com/topic/18543-compiling-tdm-204-under-linux/page-3#entry399418


git-svn-id: https://svn.thedarkmod.com/publicsvn/darkmod_src/trunk@6740 49c82d7f-2e2a-0410-a16f-ae8f201b507f